package com.example.douglaspfeifer.cinematch.ui.profile;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.provider.ContactsContract;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import com.example.douglaspfeifer.cinematch.R;
import com.example.douglaspfeifer.cinematch.ui.chat.ConversationActivity;
import com.example.douglaspfeifer.cinematch.utils.Constants;
import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.Query;
import com.firebase.client.ValueEventListener;
public class OtherProfileActivity extends AppCompatActivity {
    private Firebase mFirebaseUsersRef;
    private Firebase newChatRef;
    private Firebase newUserChatRef;
    private Firebase otherUserChatRef;
    private String mLoggedUserEmail;
    private String otherUserEmail;
    String chatId;
    Intent i;
    Button iniciarConversaButton;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_other_profile);
        if (savedInstanceState == null) {
            Bundle extras = getIntent().getExtras();
            if(extras == null) {
                otherUserEmail = null;
            } else {
                otherUserEmail = extras.getString("otherUserEmail");
            }
        } else {
            otherUserEmail = (String) savedInstanceState.getSerializable("otherUserEmail");
        }
        initializeScreen();
    }
    private void initializeScreen () {
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        // Display the button inside the toolbar
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        i = new Intent(this, ConversationActivity.class);
        mFirebaseUsersRef = new Firebase(Constants.FIREBASE_URL_USERS);

        SharedPreferences sharedPref = getSharedPreferences("settings", 0);
        mLoggedUserEmail = sharedPref.getString("userEmail", null);

        iniciarConversaButton = (Button) findViewById(R.id.iniciarConversaButton);
        setButton();
    }
    public void setButton () {
        mFirebaseUsersRef.child(mLoggedUserEmail).addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                if( otherUserEmail == null ) return;
                if (snapshot.child("chats").child(otherUserEmail).exists()) {
                    chatId = snapshot.child("chats").child(otherUserEmail).getValue().toString();
                    continuarConversa();
                }
                else {
                    iniciarConversa();
                }
            }
            @Override
            public void onCancelled(FirebaseError firebaseError) {
                System.out.println("The read failed: " + firebaseError.getMessage());
            }
        });
    }
    public void iniciarConversa () {
        iniciarConversaButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                newChatRef = new Firebase(Constants.FIREBASE_URL).child("chat").push();
                newUserChatRef = mFirebaseUsersRef.child(mLoggedUserEmail).child("chats").child(otherUserEmail);
                otherUserChatRef = mFirebaseUsersRef.child(otherUserEmail).child("chats").child(mLoggedUserEmail);
                // Get the unique ID generated by push()
                chatId = newChatRef.getKey();
                newUserChatRef.setValue(chatId);
                otherUserChatRef.setValue(chatId);
                i.putExtra("chatNode", chatId);
                i.putExtra("chatName", otherUserEmail);
                startActivity(i);
            }
        });
    }
    public void continuarConversa () {
        iniciarConversaButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                i.putExtra("chatNode", chatId);
                i.putExtra("chatName", otherUserEmail);
                startActivity(i);
            }
        });
    }
}